#!/bin/sh

RUN_CMD=${1:?CMD not found}
echo $RUN_CMD

if ! command -v $RUN_CMD > /dev/null; then 
    echo "Command not found: $RUN_CMD" 
    exit 1
fi

WATCH_DIR=${2:-$(pwd)}

restart_program() {
    pkill $RUN_CMD
    $RUN_CMD & 
}

restart_program
inotifywait -m -r -e modify --format '%w %e %T' --timefmt '%H:%M:%S' $WATCH_DIR |
    while read path event time; do 
        echo "Change detected at $time: $event $path"
        restart_program
    done
